travis: run brew update
Homebrew 1.9 appears to have broken Travis and the old versions appear
to try to update.

Error message:

```
Error: HOMEBREW_LOGS was not exported!
Please don't worry, you likely hit a bug auto-updating from an old version.
Rerun your command, everything is up-to-date and fine now.
```